# Generated by Django 4.2 on 2023-04-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('cataegory', models.CharField(max_length=35)),
                ('image', models.CharField(max_length=200)),
                ('postedby', models.EmailField(max_length=254)),
                ('highest_bid', models.IntegerField()),
                ('expire_time', models.DateTimeField()),
                ('posted_on', models.DateTimeField()),
                ('current_bidder', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='saved_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
