# Generated by Django 4.2 on 2023-04-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_saved_products_remove_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
