# Generated by Django 4.2 on 2023-04-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_products',
            name='bidded',
            field=models.BooleanField(default=False),
        ),
    ]
